# -*- coding: utf-8 -*-
"""Fall2020-CS146-HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16dQblilL6CKAe3_uhUqutpzy0uPIPj9g
"""

import sys

# To add your own Drive Run this cell.
from google.colab import drive
drive.mount('/content/drive')

# Please append your own directory after ‘/content/drive/My Drive/'
# where you have nutil.py and adult_subsample.csv
### ========== TODO : START ========== ###
# for example: sys.path += ['/content/drive/My Drive/Fall2020-CS146-HW1'] 
sys.path += ['/content/drive/My Drive/Colab Notebooks/'] 
### ========== TODO : END ========== ###

from nutil import *

# Use only the provided packages!
import math
import csv

from collections import Counter

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score
import matplotlib.pyplot as plt

######################################################################
# Immutatble classes
######################################################################

class Classifier(object) :
    """
    Classifier interface.
    """

    def fit(self, X, y):
        raise NotImplementedError()

    def predict(self, X):
        raise NotImplementedError()


class MajorityVoteClassifier(Classifier) :

    def __init__(self) :
        """
        A classifier that always predicts the majority class.

        Attributes
        --------------------
            prediction_ -- majority class
        """
        self.prediction_ = None

    def fit(self, X, y) :
        """
        Build a majority vote classifier from the training set (X, y).

        Parameters
        --------------------
            X    -- numpy array of shape (n,d), samples
            y    -- numpy array of shape (n,), target classes

        Returns
        --------------------
            self -- an instance of self
        """
        majority_val = Counter(y).most_common(1)[0][0]
        self.prediction_ = majority_val
        return self

    def predict(self, X) :
        """
        Predict class values.

        Parameters
        --------------------
            X    -- numpy array of shape (n,d), samples

        Returns
        --------------------
            y    -- numpy array of shape (n,), predicted classes
        """
        if self.prediction_ is None :
            raise Exception("Classifier not initialized. Perform a fit first.")

        n,d = X.shape
        y = [self.prediction_] * n
        return y

######################################################################
# Mutatble classes
######################################################################

class RandomClassifier(Classifier) :

    def __init__(self) :
        """
        A classifier that predicts according to the distribution of the classes.

        Attributes
        --------------------
            probabilities_ -- class distribution dict (key = class, val = probability of class)
        """
        self.probabilities_ = None

    def fit(self, X, y) :
        """
        Build a random classifier from the training set (X, y).

        Parameters
        --------------------
            X    -- numpy array of shape (n,d), samples
            y    -- numpy array of shape (n,), target classes

        Returns
        --------------------
            self -- an instance of self
        """

        ### ========== TODO : START ========== ###
        # part b: set self.probabilities_ according to the training set
        #find the proportion of over 50k, find sum of total 1s.
        over = (y==1).sum()
        self.probabilities_ = float(over) / len(y)  #find the total ratio

        ### ========== TODO : END ========== ###

        return self

    def predict(self, X, seed=1234) :
        """
        Predict class values.

        Parameters
        --------------------
            X    -- numpy array of shape (n,d), samples
            seed -- integer, random seed

        Returns
        --------------------
            y    -- numpy array of shape (n,), predicted classes
        """
        if self.probabilities_ is None :
            raise Exception("Classifier not initialized. Perform a fit first.")
        np.random.seed(seed)

        ### ========== TODO : START ========== ###
        # part b: predict the class for each test example
        # hint: use np.random.choice (be careful of the parameters)

        n,d = X.shape
        y = np.zeros(n)
        for i in range(n):         #assign each point of y a value given the weight 
            p = np.random.choice(2, 1, p=[1 - self.probabilities_, self.probabilities_]) 
            y[i] = p
        ### ========== TODO : END ========== ###

        return y

######################################################################
# Immutatble functions
######################################################################

def plot_histograms(X, y, Xnames, yname) :
    n,d = X.shape  # n = number of examples, d =  number of features
    fig = plt.figure(figsize=(20,15))
    ncol = 3
    nrow = d // ncol + 1
    for i in range(d) :
        fig.add_subplot (nrow,ncol,i+1)
        data, bins, align, labels = plot_histogram(X[:,i], y, Xname=Xnames[i], yname=yname, show = False)
        n, bins, patches = plt.hist(data, bins=bins, align=align, alpha=0.5, label=labels)
        plt.xlabel(Xnames[i])
        plt.ylabel('Frequency')
        plt.legend() #plt.legend(loc='upper left')

    plt.savefig ('histograms.pdf')


def plot_histogram(X, y, Xname, yname, show = True) :
    """
    Plots histogram of values in X grouped by y.

    Parameters
    --------------------
        X     -- numpy array of shape (n,d), feature values
        y     -- numpy array of shape (n,), target classes
        Xname -- string, name of feature
        yname -- string, name of target
    """

    # set up data for plotting
    targets = sorted(set(y))
    data = []; labels = []
    for target in targets :
        features = [X[i] for i in range(len(y)) if y[i] == target]
        data.append(features)
        labels.append('%s = %s' % (yname, target))

    # set up histogram bins
    features = set(X)
    nfeatures = len(features)
    test_range = list(range(int(math.floor(min(features))), int(math.ceil(max(features)))+1))
    if nfeatures < 10 and sorted(features) == test_range:
        bins = test_range + [test_range[-1] + 1] # add last bin
        align = 'left'
    else :
        bins = 10
        align = 'mid'

    # plot
    if show == True:
        plt.figure()
        n, bins, patches = plt.hist(data, bins=bins, align=align, alpha=0.5, label=labels)
        plt.xlabel(Xname)
        plt.ylabel('Frequency')
        plt.legend() #plt.legend(loc='upper left')
        plt.show()

    return data, bins, align, labels

######################################################################
# Mutatble functions
######################################################################

def error(clf, X, y, ntrials=100, test_size=0.2) :
    """
    Computes the classifier error over a random split of the data,
    averaged over ntrials runs.

    Parameters
    --------------------
        clf         -- classifier
        X           -- numpy array of shape (n,d), features values
        y           -- numpy array of shape (n,), target classes
        ntrials     -- integer, number of trials

    Returns
    --------------------
        train_error -- float, training error
        test_error  -- float, test error
        f1_score    -- float, test "micro" averaged f1 score
    """

    ### ========== TODO : START ========== ###
    # compute cross-validation error over ntrials

    #initialize the error trackers to 0
    Train_error = 0
    Test_error = 0

    for i in range(ntrials):
        #first split the data into train and test split. 
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = test_size, random_state=0)
        clf.fit(X_train,y_train)
        y_pred = clf.predict(X_train)

        #With the training y_pred, we can test its accuracy against the y_train
        train_error = 1 - metrics.accuracy_score(y_train, y_pred, normalize=True)
        Train_error += train_error

        #Now we move on to predicting the y using testing data
        #compare the y testing data with the predicted y from X_test
        y_pred = clf.predict(X_test)
        test_error = 1 - metrics.accuracy_score(y_test, y_pred, normalize=True)
        Test_error += test_error

    #grab the average errors and f1
    Train_error = float(Train_error)/((1-test_size) * len(y))
    Test_error = float(Test_error)/(test_size * len(y))
    f1 = f1_score(y_test, y_pred, average='micro')
  
    ### ========== TODO : END ========== ###
    return train_error, test_error, f1

######################################################################
# Immutatble functions
######################################################################


def write_predictions(y_pred, filename, yname=None) :
    """Write out predictions to csv file."""
    out = open(filename, 'wb')
    f = csv.writer(out)
    if yname :
        f.writerow([yname])
    f.writerows(list(zip(y_pred)))
    out.close()

######################################################################
# main
######################################################################

def main():
    
    
    
    # load adult_subsample dataset with correct file path
    ### ========== TODO : START ========== ###
    data_file =  "/content/drive/My Drive/Colab Notebooks/adult_subsample.csv"
    ### ========== TODO : END ========== ###
    

    data = load_data(data_file, header=1, predict_col=-1)

    X = data.X; Xnames = data.Xnames
    y = data.y; yname = data.yname
    n,d = X.shape  # n = number of examples, d =  number of features

    
    '''
    plt.figure()

    #========================================
    # part a: plot histograms of each feature
    print('Plotting...')
    plot_histograms (X, y, Xnames=Xnames, yname=yname)
    '''




    ### ========== TODO : START ========== ###
    # part i: Preprocess X (e.g., normalize)
    X = preprocessing.normalize(X, norm='l2')


    
    ### ========== TODO : END ========== ###




    #========================================
    # train Majority Vote classifier on data
    print('Classifying using Majority Vote...')
    clf = MajorityVoteClassifier() # create MajorityVote classifier, which includes all model parameters
    clf.fit(X, y)                  # fit training data using the classifier
    y_pred = clf.predict(X)        # take the classifier and run it on the training data
    train_error = 1 - metrics.accuracy_score(y, y_pred, normalize=True)
    print('\t-- training error: %.3f' % train_error)





    ### ========== TODO : START ========== ###
    # part b: evaluate training error of Random classifier
    print('Classifying using Random...')
    clf = RandomClassifier()       # create Random classifier, which includes all model parameters
    clf.fit(X, y)                  # fit training data using the classifier
    y_pred = clf.predict(X)        # take the classifier and run it on the training data
    train_error = 1 - metrics.accuracy_score(y, y_pred, normalize=True)
    print('\t-- training error: %.3f' % train_error)

    ### ========== TODO : END ========== ###





    ### ========== TODO : START ========== ###
    # part c: evaluate training error of Decision Tree classifier
    print('Classifying using Decision Tree...')

    #assign the classifier as decision tree using entropy
    clf = DecisionTreeClassifier(criterion="entropy")
    clf.fit(X,y)
    y_pred = clf.predict(X)
    train_error = 1 - metrics.accuracy_score(y, y_pred, normalize=True)
    print('\t-- training error: %.3f' % train_error)
    ### ========== TODO : END ========== ###




    ### ========== TODO : START ========== ###
    # part d: evaluate training error of k-Nearest Neighbors classifier
    # use k = 3, 5, 7 for n_neighbors
    print('Classifying using k-Nearest Neighbors...')

    k = [3, 5, 7]
    for size in k:
          clf = KNeighborsClassifier(n_neighbors = size)
          clf.fit(X,y)
          y_pred = clf.predict(X)
          train_error = 1 - metrics.accuracy_score(y, y_pred, normalize=True)
          print('\t-- training error for k = %d: %.3f' % (size, train_error))

    ### ========== TODO : END ========== ###





    ### ========== TODO : START ========== ###
    # part e: use cross-validation to compute average training and test error of classifiers
    print('Investigating various classifiers...')

    #For the four models we already have, we display each train and test error, also the f1 score
    clf = MajorityVoteClassifier() 
    train_err, test_err, f1 = error(clf, X, y, ntrials=100)
    print ("Majority Vote Classifier: train_err: %.3f, test_err: %.3f, F1: %.3f" % (train_err, test_err, f1))

    clf = RandomClassifier() 
    train_err, test_err, f1 = error(clf, X, y, ntrials=100)
    print ("Random Classifier       : train_err: %.3f, test_err: %.3f, F1: %.3f" % (train_err, test_err, f1))

    clf = DecisionTreeClassifier(criterion="entropy") 
    train_err, test_err, f1 = error(clf, X, y, ntrials=100)
    print ("Decision Tree Classifier: train_err: %.3f, test_err: %.3f, F1: %.3f" % (train_err, test_err, f1))

    clf = KNeighborsClassifier(n_neighbors=5)
    train_err, test_err, f1 = error(clf, X, y, ntrials=100)
    print ("K Neighbors Classifier  : train_err: %.3f, test_err: %.3f, F1: %.3f" % (train_err, test_err, f1))

    ### ========== TODO : END ========== ###





    ### ========== TODO : START ========== ###
    # part f: use 10-fold cross-validation to find the best value of k for k-Nearest Neighbors classifier
    print('Finding the best k...')

    #create 10 folds
    Folds = 10

    #declare empty array for knn values and k values
    knn =[]
    k = []
    #since we will skip all the even numbers, make the jump 2 (1~49) 
    for i in range (1,50,2):
        k.append(i)
        clt = KNeighborsClassifier(n_neighbors = i)
        cv_score = cross_val_score(clt , X, y, cv = Folds )
        curr_avg = cv_score.mean()  
        knn.append(curr_avg)

    #now that I have the arrays populated, we can use matlab to print
    plt.plot(k, knn)
    plt.xlabel("K")
    plt.ylabel("Performance")
    plt.show()

    ### ========== TODO : END ========== ###





    ### ========== TODO : START ========== ###
    # part g: investigate decision tree classifier with various depths
    print('Investigating depths...')

    #declare empty array for x, avg training error, and test error
    x = []
    avg_t = []
    test_e = []
    #Run through each one to find the values, record them
    for i in range (1,21):
        x.append(i)
        clf = DecisionTreeClassifier(criterion="entropy", max_depth=i)
        train_err, test_err, f1 = error(clf, X, y, ntrials=100)
        avg_t.append(train_err)
        test_e.append(test_err)

    #now that I have the arrays populated, we can use matlab to print
    plt.plot(x, avg_t, x, test_e )
    plt.xlabel("Max Depth")
    plt.ylabel("Error")
    plt.title('Investigating Depth')
    labels = ['Avg Train Error', 'Test Error']
    plt.legend(labels)
    plt.show()

    

    ### ========== TODO : END ========== ###





    ### ========== TODO : START ========== ###
    # part h: investigate decision tree and k-Nearest Neighbors classifier with various training set sizes
    #first, split the data into 90% training and 10% testing
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

    #declare the empty arrays that we will populate soon
    tree_arr_train =[]
    tree_arr_test = []
    knn_arr_train = []
    knn_arr_test =  []

    #since we will be traversing  from 10% to 90%, we will need a step tracker
    step = []
    for i in range(1, 11):
      step.append(float(i) / 10 )
      #print(step[i-1])

    for i in step:
        #we will split the training slowly from 10% to 100%

        #just some error handling, it seems test size has to be between 0 and 1
        if i == 1:
          train_x, test_x, train_y, test_y = train_test_split(X_train, y_train, test_size= 0.000001)
        else: 
          train_x, test_x, train_y, test_y = train_test_split(X_train, y_train, test_size=1-i)

        #Start the process for decision tree
        clf1 = DecisionTreeClassifier(criterion="entropy", max_depth= 4)
        train_err, test_err, f1 = error(clf1, train_x, train_y, ntrials=100)
        #collect the errors and append to array
        tree_arr_train.append(train_err)
        tree_arr_test.append(test_err)

        #Start the process for KNN 
        clf2 = KNeighborsClassifier(n_neighbors= 16)
        train_err, test_err, f1 = error(clf2, train_x, train_y, ntrials=100)
        #collect the errors and append to array
        knn_arr_train.append(train_err)
        knn_arr_test.append(test_err)

    #graph all four arrays on the same plot with different colors with a legend
    plt.plot(step, tree_arr_train , 'r', label="Tree Training Error")
    plt.plot(step, tree_arr_test , 'g', label="Tree Testing Error")
    plt.plot(step, knn_arr_train , 'b', label="KNN Train Error")
    plt.plot(step, knn_arr_test , 'y', label="KNN Test Error")
    plt.xlabel("Ratio of Training Data")
    plt.ylabel("Error Value")
    labelsh = ["Tree Training Error","Tree Testing Error" , "KNN Train Error", "KNN Test Error" ]
    plt.legend(labelsh)
    plt.show()

    ### ========== TODO : END ========== ###

    print('Done')


if __name__ == "__main__":
    main()