# -*- coding: utf-8 -*-
"""Fall2020-CS146-HW4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tVEJtUiyW11KVihYP-mQOPsI7O78NPk0
"""

# To add your own Drive Run this cell.
from google.colab import drive
drive.mount('/content/drive')

"""
Author      : Zeyuan Chen, adapted from Yi-Chieh Wu, Sriram Sankararman
Description : Twitter
"""

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn import metrics 
from sklearn.svm import SVC
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.mixture import GaussianMixture
from sklearn.metrics.cluster import adjusted_rand_score
from sklearn.metrics import f1_score

import pandas as pd
### ========== TODO : START ========== ###
# append you own path to the tweeter_df.txt file after "/content/drive/My Drive/"
# i.e. "/content/drive/My Drive/CM146HW4/tweets_df.txt"
tweets_df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/tweets_df.txt", index_col = 0)
### ========== TODO : END ========== ###

X = tweets_df.values[:,:-2]
y = tweets_df.values[:, -2]
movies = tweets_df.values[:, -1]

train_idx = np.where((movies == 1) | (movies == 3))[0]
dev_idx   = np.where(movies == 2)[0]
test_idx  = np.where(movies == 0)[0]

X_train, X_dev, X_test = X[train_idx,], X[dev_idx,], X[test_idx,]
y_train, y_dev, y_test = y[train_idx,], y[dev_idx,], y[test_idx,]

### ========== TODO : START ========== ###
# part 4.1a: show the train and development set f1-score when C is set to 10^-3 10^-2 10^-1 1, 10, 100, 1000
#            This can typically be done in 20 lines or so

#from the professor:
Cv  = 10.0 ** np.arange(-3, 4)
f_train = []
f_dev = []

#For every C, find the f1 score of train and dev...
for c in Cv:
  clf = SVC (kernel='linear', C = c)
  clf.fit (X_train, y_train)
  y_pred = clf.predict(X_train)
  f_train.append(f1_score(y_train, y_pred, average='binary'))
  
  y_pred = clf.predict(X_dev)
  f_dev.append(f1_score(y_dev, y_pred, average='binary'))

#start plotting!
plt.plot(f_train, 'r',  label = "train f1-score")
plt.plot(f_dev, 'g',    label = "dev f1-score")
plt.xticks(np.arange(8), C_range)
plt.xlabel("C Range")
plt.ylabel("F1-Score")
labelsh = ["Training Score", "Dev Score"]
plt.legend(labelsh)
plt.show()


### ========== TODO : END ========== ###

### ========== TODO : START ========== ###
# part 4.1b: select the best model based on development set f1-score 
#            retrain the model on train and dev set
#            test the final model on the test set
#            This can typically be done in 5 lines or so


#Now that we know that C = 1, we can use it to train the entire
#Dataset...
X_train = np.concatenate((X_train, X_dev), axis = 0)
y_train = np.concatenate((y_train, y_dev), axis = 0)

clf = SVC (kernel='linear', C = 1)
clf.fit (X_train, y_train)
y_pred = clf.predict(X_test)
fscore = f1_score(y_test, y_pred, average='binary')
print('The f1-score after fitting with training on testing: %.4f' %(fscore))


### ========== TODO : END ========== ###

def plot_scatter(embedding_2d, labels, show = True, save_as = None, title = None):
    """
    Visualize 2D data

    Parameters
    --------------------
        embedding_2d   -- numpy array of shape (n,2) samples
        labels         -- numpy array of shape (n,) labels
        show           -- optional boolean indicator on if display the visualziation, default set to True 
        save_as        -- optional string indicating where we should save the figure, default set to None
        title          -- optional string indicating what should be the title, default set to None
    --------------------
        None    
    """
    
    plt.scatter(embedding_2d[:,0], embedding_2d[:,1], c = labels) 
    if title is not None:
        plt.title(title)
    if save_as is not None:
        plt.savefig(save_as)
    if show:
        plt.show()

pca = PCA(n_components=2)
pca.fit(X)
X_embedding = pca.transform(X)

### ========== TODO : START ========== ###
# part 4.2a: visualize the embedding. First color the dots by positive or negative review, then by movies 
#            This can typically be done in 2 lines or so

plot_scatter(X_embedding, labels = y)
plot_scatter(X_embedding, labels = movies)

### ========== TODO : END ========== ###

### ========== TODO : START ========== ###
# part 4.2b: First color the dots by Kmeans with 4 components, random initialization, 1 iteration, random_state = 2
#            then by GMM with 4 components, random starting point, 1 iteration and random_state = 0
#            report the adjusted rand score for both
#            This can typically be done in 10 lines or so

#start the fit
kmeans = KMeans(n_clusters = 4,  init = 'random', n_init = 1, random_state= 2).fit(X_embedding)
#Visualize the low dimensional data by labeling/coloring each tweet with Kmeans results. 
plot_scatter(X_embedding, labels = kmeans.predict(X_embedding))
#Calculate the adjusted rand score
print('The adjusted random score for k-means: %.4f' %(adjusted_rand_score(kmeans.predict(X_embedding), movies)))

#start the fit
gauss = GaussianMixture(n_components=4, random_state = 0 , init_params='random').fit(X_embedding)
#Visualize the low dimensional data by labeling/coloring each tweet with Gauss results.
plot_scatter(X_embedding, labels = gauss.predict(X_embedding))
#Calculate the adjusted rand score
print('The adjusted random score for Gauss Mix: %.4f' %( adjusted_rand_score(gauss.predict(X_embedding), movies)  ))

### ========== TODO : END ========== ###

### ========== TODO : START ========== ###
# part 4.2c: First color the dots by Kmeans with 4 components, random initialization, 100 iterations, random_state = 2
#            then by GMM with 4 components, random starting point, 100 iterations and random_state = 0
#            report then adjusted rand score for both
#            This can typically be done in 10 lines or so

#start the fit
kmeans = KMeans(n_clusters = 4,  init = 'random', n_init = 100, random_state= 2).fit(X_embedding)
#Visualize the low dimensional data by labeling/coloring each tweet with Kmeans results. 
plot_scatter(X_embedding, labels = kmeans.predict(X_embedding))
#Calculate the adjusted rand score
print('The adjusted random score for k-means: %.4f' %(adjusted_rand_score(kmeans.predict(X_embedding), movies)))

#start the fit
gauss = GaussianMixture(n_components=4, random_state = 0 , init_params='random', n_init = 100).fit(X_embedding)
#Visualize the low dimensional data by labeling/coloring each tweet with Gauss results.
plot_scatter(X_embedding, labels = gauss.predict(X_embedding))
#Calculate the adjusted rand score
print('The adjusted random score for Gauss Mix: %.4f' %( adjusted_rand_score(gauss.predict(X_embedding), movies)  ))

### ========== TODO : END ========== ###